---
- hosts: all
  sudo: true
  remote_user: root

  tasks:

  - name: Include OS-Specific variables
    include_vars: "jenkins.yml"
  - name: Ensure Jenkins repo is installed.
    get_url:
      url: "{{ jenkins_repo_url }}"
      dest: /etc/yum.repos.d/jenkins.repo

  - name: Add Jenkins repo GPG key.
    rpm_key:
      state: present
      key: "{{ jenkins_repo_key_url }}"

  - name: install java
    yum: pkg=java state=latest

  - name: install tomcat
    yum: pkg=tomcat state=latest

  - name: install epel-release
    yum: pkg=epel-release state=latest

  - name: install maven
    yum: pkg=maven2 state=latest

  - name: install git
    yum: pkg=git state=latest

  - name: install nginx
    yum: pkg=nginx state=latest

  - name: install jenkins
    yum: pkg=jenkins state=latest

#  - name: change nginx default config
#    template: src=files/nginx.conf.j2 dest=/etc/nginx/nginx.conf

  - name: start jenkins
    service: name=jenkins state=started enabled=yes

  - name: start nginx
    service: name=nginx state=started enabled=yes


